stages:
  - build-n-push

build-n-push:
  stage: build-n-push
  tags:
    - docker
  services:
    - docker:dind
  image: docker
  script:
    - git clone https://gitlab.com/lappis-unb/decidimbr/servicos-de-dados/airflow-dags
    - docker login $CI_REGISTRY -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD"
    - docker build -t $CI_REGISTRY_IMAGE .
    - docker push $CI_REGISTRY_IMAGE
  only:
    changes:
      - Dockerfile
      - requirements.txt