#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
	CREATE USER ${POSTGRES_USER_DW} WITH PASSWORD '${POSTGRES_PASSWORD_DW}';
	CREATE DATABASE ${POSTGRES_DB_DW};
	GRANT ALL PRIVILEGES ON DATABASE ${POSTGRES_DB_DW} TO ${POSTGRES_USER_DW};
EOSQL